server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: google-service
          uri: https://www.google.com
          predicates:
            - Method=GET
            - Path=/google/**
          filters:
            - name: StripPrefix
              args:
                parts: 2
            - name: Auth
              args:
                  name: "auth argument"
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
